In [ ]:
# Introduction to Numpy ---------->
# NumPy is an open-source library that is used for handle scientific calculations.

# Difference between List And NumPy ------>
# 1). List Hetrogeneous data type and NumPy is Homogenous data type.
# 2). List takes more memory as compare to NumPy.
# 3). List takes more execution time as compare to NumPy.

In [ ]:
# pip instal numpy              -----> for vs code
# !pip install numpy            -----> for jupyter notebook
# uv add -r requirements.txt    -----> for uv in vs code

In [2]:
import numpy as np

In [3]:
a = [1,45,78,90]
type(a)

list

In [4]:
b = np.array(a)
b

array([ 1, 45, 78, 90])

In [5]:
type(b)

numpy.ndarray

In [ ]:
#### User Defined Array

In [9]:
a = []
size = int(input("Enter size:"))
for i in range(size):
  val = int(input("Enter item:"))
  a.append(val)
# print(a)
b = np.array(a)
b

Enter size:4
Enter item:56
Enter item:55
Enter item:1
Enter item:2


array([56, 55,  1,  2])

In [10]:
type(b)

numpy.ndarray

In [12]:
a = [[1,2,3],[4,5,6],[7,8,9]]
# a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
b = np.array(a)
# b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#  Matrix ---------> rows, columns

# row_1 = [1,2,3]
# row_2 = [4,5,6]
# row_3 = [7,8,9]

# col_1 = [1,4,7]
# col_2 = [2,5,8]
# col_3 = [3,6,9]

# Total Elements = row*column = 3*3 = 9

In [14]:
print("Total Rows And Columns :" , b.shape)
print("Total Elements", b.size)

Total Rows And Columns : (3, 3)
Total Elements 9


In [15]:
a = [[1,2,3,5],[4,5,6,8],[7,8,9,10]]
b = np.array(a)
b

array([[ 1,  2,  3,  5],
       [ 4,  5,  6,  8],
       [ 7,  8,  9, 10]])

In [16]:
print("Total Rows And Columns :" , b.shape)
print("Total Elements", b.size)

Total Rows And Columns : (3, 4)
Total Elements 12


In [ ]:
#  How to check dimension of an matrix?

In [17]:
a = np.array([1,3,4])
a

array([1, 3, 4])

In [18]:
a.ndim

1

In [22]:
a = np.array([[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [23]:
a.ndim

3

In [ ]:
# Images   ----> Pixels(0-255)      ----> Matrix        ----> Operations
# DL       ----> Artificial Neurons ----> Weight        ----> Randomly Creation ----> NumPy
# Datasets ----> Dummy Entry        ----> Random Module ----> Atttach Panda's

In [ ]:
# Pre-defined Function in NumPy

In [ ]:
# 1). Zeros() ----> It will create an array in which all the values will be
#  one in either 1-D or Multi-Dimensional

In [24]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [25]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
a.shape

(3, 4)

In [ ]:
# 2). Ones() ----> It will create an array in which all the values will be 1
#  in either 1-D or Multi-Dimensional

In [28]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [29]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
a.shape

(4, 5)

In [31]:
a.size

20