In [1]:
import  numpy as np

In [2]:
a = np.array([1,45,78])
a

array([ 1, 45, 78])

In [3]:
a.shape

(3,)

In [4]:
a.size

3

In [5]:
a.ndim

1

In [6]:
# (1). zeros() --->
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
# (2). ones() ---->
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
# (3). eye() ---> It will create an array in which digonal positional elements will be
# 1 and rest all are 0 .

In [9]:
a = np.eye(3)   ### rows = columns ---> Symmetric Matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
a = np.eye(3,4)   ### rows != columns ---> Asymmetric Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
# (4). diag() ---> It will create an array in which we can set our custom values at
# digonal position .

In [12]:
a = np.diag([1,34,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [14]:
# (5). Random Module --->
# (a). Randint() ---> It will create an array randomly in a given range .
# syntax : np.random.randint(min_range, max_range, total_numbers)

In [21]:
a = np.random.randint(1,10,3)
a

array([2, 7, 6])

In [18]:
# (b). rand() ----> It will generate random numbers from 0-1.
# syntax : np.random.rand(total_random_numbers)

In [20]:
a = np.random.rand(4)
a

array([0.57638635, 0.84044704, 0.69181794, 0.2962793 ])

In [ ]:
# (c).
# dataset(emp_data)(emp-id, salary , domain) ---> randomly column add (working_hours)

In [22]:
# (c). seed() ---> It will fix or lock our generated data.
# syntax :
# np.random.seed(45)
# a = np.random.randint(1,10,2)

In [37]:
np.random.seed(34)
a = np.random.randint(1,10,3)
a

array([2, 7, 6])

In [38]:
# View Vs Copy

In [39]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [41]:
b = a[1:4]
b[:] = 0
b

array([0, 0, 0])

In [42]:
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [43]:
# copy

In [46]:
a = np.array([10,20,30,40,50,60,70,80])
b  = a[1:4].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [47]:
# Reshaping the Array
# total rows * columns = total_elements

In [48]:
a = np.random.randint(1,50,12)
a

array([ 5, 36,  6, 12, 43, 15, 30, 19, 30, 26, 30, 39])

In [49]:
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3

In [52]:
a.reshape(2,6)

array([[ 5, 36,  6, 12, 43, 15],
       [30, 19, 30, 26, 30, 39]])

In [54]:
a.reshape(3,4)

array([[ 5, 36,  6, 12],
       [43, 15, 30, 19],
       [30, 26, 30, 39]])

In [57]:
# a.reshape(6,3)

In [ ]:
# y = mx + b
# m = matrix  ---. weights
# x  = values --> matrix

# matrix(column) * (row)matrix

In [59]:
a.shape

(12,)

In [60]:
a.reshape(-1,3)

array([[ 5, 36,  6],
       [12, 43, 15],
       [30, 19, 30],
       [26, 30, 39]])

In [62]:
a.reshape(2,-1)

array([[ 5, 36,  6, 12, 43, 15],
       [30, 19, 30, 26, 30, 39]])

In [63]:
# Operations on Array

In [66]:
a = np.arange(1,5,2)
a

array([1, 3])

In [70]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [71]:
a*2

array([2, 4, 6, 8])

In [73]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [78]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [79]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [80]:
a+b

array([[ 6,  8],
       [10, 12]])

In [81]:
a-b

array([[-4, -4],
       [-4, -4]])

In [83]:
a

array([[1, 2],
       [3, 4]])

In [84]:
b

array([[5, 6],
       [7, 8]])

In [85]:
# 1*5+2*7   1*6+2*8

In [86]:
a.dot(b)    ### this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [95]:
 a = np.arange(1,15)
 a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [107]:
b = a%2==0
a[b]

array([2, 4, 6, 8])

In [92]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [93]:
a**3

array([ 1,  8, 27])

In [99]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.sum(a)

np.int64(45)

In [104]:
np.sum(a , axis = 1)    ### axis= 1 means row wise operation

array([ 6, 15, 24])

In [106]:
np.sum(a , axis=0)     ### axis=0 means column wise operation

array([12, 15, 18])