In [1]:
import numpy as np

In [ ]:
# Unique() ----> It will create an array in which it will remove duplicate values and
# it will return 3 arrays :
# arr ----> Unique elements of array
# return_index = True ----> Indexing of Unique element
# return_counts = True ----> Frequency of each unique element.

In [2]:
a = np.array([1,2,3,1,1,1,4,5,4,4,4,4,4,4,6,7])
a

array([1, 2, 3, 1, 1, 1, 4, 5, 4, 4, 4, 4, 4, 4, 6, 7])

In [5]:
b = np.unique(a , return_index = True, return_counts = True)


In [4]:
b

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  6,  7, 14, 15]),
 array([4, 1, 1, 7, 1, 1, 1]))

In [ ]:
# Linspace() ----> It will return an array in which elements will be same gap in a given range.
# Syntax : np.linspace(min_num , max_num, total_numbers)

In [6]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Horizontal And Vertical Stacking ---->
# Horizontal Stacking ----> It will add 2 or more arrays in horizontally

In [10]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [11]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [12]:
c = np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [13]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])